### ISSUE TITLE
As a User, I can see data about my reading activity to gain insights into my reading habits

### ISSUE THREAD

**Issue by dleistman** [DJA1802/readMe#74]
- [x] meet as a group to figure out approach
- [x] #56 Research/formulate strategy for capturing startTime and endTime of user interaction with article
- [x] #76 As a User, I can see what publications my articles are from
- [x] #132 Add key analytics/statistics to home page 
- [x] #148 Fill out "Article Data" tab in "My Data" with tables of information regarding most-read articles

Nice to have:
- #82 As a User, I can see relevant tags for each of my articles
- #79 Incorporate user idle time into interaction logic

**Comment by dleistman** [comment]
Seems like we should start with most basic charts
- Line (or bar) chart -- reading hours per day/week/month (can later filter by topic, etc)
- Pie chart -- proportion of time spent on certain publications (can later do topics, etc)
